#!/bin/bash

# check if working tree is clean
# https://unix.stackexchange.com/questions/155046/determine-if-git-working-directory-is-clean-from-a-script
if [ -z "$(git status --porcelain)" ] 
then
    # go to root of project 
    # https://stackoverflow.com/questions/957928/is-there-a-way-to-get-the-git-root-directory-in-one-command#comment56434319_957928
    cd $(git rev-parse --show-toplevel)

    # pull changes
    git pull

    # neovim
    git switch neovim
    rm -rf ./init.lua ./lua/nv/ ./ftplugin/
    cp -r ~/.config/nvim/init.lua ~/.config/nvim/ftplugin/ .
    cp -r  ~/.config/nvim/lua/nv/ ./lua/
    git add .
    git commit -m 'automated neovim sync'
    
    # tmux
    git switch tmux
    cp ~/.tmux.conf .
    git add .tmux.conf
    git commit -m 'automated tmux sync'

    # bash
    git switch bash
    cp ~/.bashrc .
    cp ~/.inputrc .
    git add .bashrc .inputrc
    git commit -m 'automated bash sync'

    # git
    git switch git
    cp ~/.gitconfig .
    git add .gitconfig
    git commit -m 'automated git sync'

    # vim
    git switch vim
    cp ~/.vimrc .
    git add .vimrc
    git commit -m 'automated vim sync'

    # neofetch
    git switch neofetch
    cp ~/.config/neofetch/config.conf .
    git add config.conf
    git commit -m 'automated neofetch sync'

    # helix
    git switch helix
    cp ~/.config/helix/config.toml .
    git add config.toml
    git commit -m 'automated helix sync'

    # dnf
    git switch dnf
    cp /etc/dnf/dnf.conf .
    git add dnf.conf .
    git commit -m 'automated dnf sync'

    # main
    git switch main

    # remote (origin)
    git push origin main neovim tmux bash git vim neofetch helix dnf
else
    echo 'workingtree dirty'
fi
